var homePage = document.getElementById("homePage");
var subMenuPageHeading = document.getElementById("subMenuPageHeading");
var subHeading = document.getElementById("subHeading");
var input1 = document.getElementById("input1");
var input1Label = document.getElementById("input1Label");
var input2 = document.getElementById("input2");
var input2Label = document.getElementById("input2Label");
var referance = document.getElementById("subMenuPageHeading");
var subMenuPageUp_routeHeading = document.getElementById("subMenuPageUp_routeHeading");
var subMenuPageDown_routeHeading = document.getElementById("subMenuPageDown_routeHeading");
var subMenuPageUp = document.getElementById("subMenuPageUp");
var subMenuPageDown = document.getElementById("subMenuPageDown");
var subMenuPageUp_UL = document.getElementById("subMenuPageUp_UL");
var subMenuPageDown_UL = document.getElementById("subMenuPageDown_UL");
var routeDetailsNoteUp = document.getElementById("routeDetailsNoteUp");
var routeDetailsNoteDown = document.getElementById("routeDetailsNoteDown");
var btnExpandUp = document.getElementById("btnExpandUp");
var btnExpandDown = document.getElementById("btnExpandDown");
var subMenuPageBSD = document.getElementById("subMenuPageBSD");
var subMenuPageBSD_routeHeading = document.getElementById("subMenuPageBSD_routeHeading");
var subMenuPageALT = document.getElementById("subMenuPageALT");
var subMenuPageALT_routeHeading = document.getElementById("subMenuPageALT_routeHeading");
var structureALT1 = document.getElementById("structureALT1");
var structureALT2 = document.getElementById("structureALT2");
var art_row_1_1 = document.getElementById("art_row_1_1");
var art_row_1_2 = document.getElementById("art_row_1_1");
var art_row_2_1 = document.getElementById("art_row_2_1");
var art_row_2_2 = document.getElementById("art_row_2_1");
var subMenuPageFD = document.getElementById("subMenuPageFD");
var subMenuPageFD_routeHeading = document.getElementById("subMenuPageFD_routeHeading");
var note = document.getElementById("note");
var noteText = document.getElementById("noteText");
var FD_co = document.getElementById("FD_co");
var FD_me = document.getElementById("FD_me");
var subMenuPage = document.getElementById("subMenuPage");
var subMenuPageUp = document.getElementById("subMenuPageUp");
var subMenuPageDown = document.getElementById("subMenuPageDown");
var homePage = document.getElementById("homePage");
var subMenuPageBSD = document.getElementById("subMenuPageBSD");
var subMenuPageALT = document.getElementById("subMenuPageALT");
var subMenuPageFD = document.getElementById("subMenuPageFD");
var note = document.getElementById("note");
var btnGet = document.getElementById("btnGet");
var input1 = document.getElementById("input1");
var input1 = document.getElementById("input1");
var routeDetailsNoteUp = document.getElementById("routeDetailsNoteUp");
var routeDetailsNoteDown = document.getElementById("routeDetailsNoteDown");
var input1 = document.getElementById("input1");
var routeDetailsNoteUp = document.getElementById("routeDetailsNoteUp");
var routeDetailsNoteDown = document.getElementById("routeDetailsNoteDown");
var subMenuPage = document.getElementById("subMenuPage");
var subMenuPageUp = document.getElementById("subMenuPageUp");
var subMenuPageDown = document.getElementById("subMenuPageDown");
var homePage = document.getElementById("homePage");
var subMenuPageBSD = document.getElementById("subMenuPageBSD");
var subMenuPageALT = document.getElementById("subMenuPageALT");
var subMenuPageFD = document.getElementById("subMenuPageFD");
var note = document.getElementById("note");
var input1 = document.getElementById("input1");
var btnGet = document.getElementById("btnGet");
var subMenuPage = document.getElementById("subMenuPage");
var subMenuPageUp = document.getElementById("subMenuPageUp");
var subMenuPageDown = document.getElementById("subMenuPageDown");
var homePage = document.getElementById("homePage");
var subMenuPageBSD = document.getElementById("subMenuPageBSD");
var subMenuPageALT = document.getElementById("subMenuPageALT");
var subMenuPageFD = document.getElementById("subMenuPageFD");
var note = document.getElementById("note");
var input1 = document.getElementById("input1");
var btnGet = document.getElementById("btnGet");








if (input1.value === "1") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1/25S") {
    arrayHUP = SEC_RTCX_UP.concat(["BUS BHAVAN", "VST"], NLK_KCG_UP, ["NIMBOLI ADDA", "CHADERGHAT", "CITY BUS STATION", "AFZALGUNJ"])
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1B") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1C") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1D") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1D/229") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1D/299") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1H/D") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1J") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1K") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1L") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1M/D") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1P") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1P/25S") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1V") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1X") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1Z") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "1Z/229") {
    arrayHUP = SEC_RTCX_UP.concat(RTCX_YMCA_UP, KCGX_AFZ_UP);
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "2") {
    arrayHUP = SEC_RTCX_UP.concat(["BUS BHAVAN", "VST"], NLK_KCG_UP, ["NIMBOLI ADDA", "CHADERGHAT", "CITY BUS STATION", "AFZALGUNJ"])
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "2/25S") {
    arrayHUP = SEC_RTCX_UP.concat(["BUS BHAVAN", "VST"], NLK_KCG_UP, ["NIMBOLI ADDA", "CHADERGHAT", "CITY BUS STATION", "AFZALGUNJ"])
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "2C") {
    arrayHUP = SEC_RTCX_UP.concat(["BUS BHAVAN", "VST"], NLK_KCG_UP, ["NIMBOLI ADDA", "CHADERGHAT", "CITY BUS STATION", "AFZALGUNJ"])
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "2J") {
    arrayHUP = SEC_RTCX_UP.concat(["BUS BHAVAN", "VST"], NLK_KCG_UP, ["NIMBOLI ADDA", "CHADERGHAT", "CITY BUS STATION", "AFZALGUNJ"])
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "2K") {
    arrayHUP = SEC_RTCX_UP.concat(["BUS BHAVAN", "VST"], NLK_KCG_UP, ["NIMBOLI ADDA", "CHADERGHAT", "CITY BUS STATION", "AFZALGUNJ"])
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "2U") {
    arrayHUP = SEC_RTCX_UP.concat(["BUS BHAVAN", "VST"], NLK_KCG_UP, ["NIMBOLI ADDA", "CHADERGHAT", "CITY BUS STATION", "AFZALGUNJ"])
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "2Z") {
    arrayHUP = SEC_RTCX_UP.concat(["BUS BHAVAN", "VST"], NLK_KCG_UP, ["NIMBOLI ADDA", "CHADERGHAT", "CITY BUS STATION", "AFZALGUNJ"])
    arraySHUP = ["RETHIFILE BUS STATION || RAILWAY STATION", "RAILWAY COACH STATION", "HOSPITAL || MEDICAL COLLEGE", "POLICE STATION", "SRI SAI RAJA THEATER", "X ROADS", "SAPTHAGIRI THEATER || SANDHYA THEATER", "POLICE STATION || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "3K") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3C") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3D") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3DN") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3H") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3HN") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3K") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3K/92A") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3K/102B") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3K/242") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3K/252") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3K/281") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3KN") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3KN/102B") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3KJ") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3L") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3M") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3N") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3N/203A") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3T") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}
else if (input1.value === "3Y") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(ARTS_AFZAL_UP);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "block";
}

else if (input1.value === "10H") {
    arrayHUP = ["SECUNDERABAD", "PATNY", "SWIMMING POOL", "PARADISE", "POLICE LINES", "RASOOLPURA", "PRAKASH NAGAR", "BEGUMPET", "SHYAMLAL", "HYD PUBLIC SCHOOL", "GREENLANDS", "LAL BUNGLOW", "SHESHMAHAL", "AMEERPET", "SATYAM X ROADS", "MYTHRIVANAM", "MADHURA NAGAR", "YOUSUFGUDA CHECKPOST", "YOUSUFGUDA", "KRISHNA NAGAR", "JUBLIEE CHECKPOST", "KOTHAGUDA", "KONDAPUR"]
    arraySHUP = ["RAILWAY STATION || ALPHA HOTEL", "SURYA TOWERS || METRO STATION", "UNDEFINDED", "HOTEL || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "49M") {
    arrayHUP = ["SECUNDERABAD", "PATNY", "SWIMMING POOL", "PARADISE", "POLICE LINES", "RASOOLPURA", "PRAKASH NAGAR", "BEGUMPET", "SHYAMLAL", "HYD PUBLIC SCHOOL", "GREENLANDS", "PANJAGUTTA", "NIMS HOSPITAL", "VENGAL RAO PARK", "MASAB TANK", "MEHDIPATNAM"]
    arraySHUP = ["RAILWAY STATION || ALPHA HOTEL", "SURYA TOWERS || METRO STATION", "UNDEFINDED", "HOTEL || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "17H") {
    arrayHUP = ECIL_TNK_LPT_UP.concat(["RAILWAY DEGREE COLLEGE", "METTUGUDA", "ALUGADDA BHAVI", "SANGEETH", "SECUNDERABAD"]);
    arraySHUP = ["TALLURI THEATERS", "KUSHAIGUDA PS || BUS STATION", "KUSHAIGUDA DEPOT", "HOSPITAL", "LAXMI NAGAR", "HB COLONY || 2ND PHASE", "DEGREE COLLEGE || MANGAPURAM", "PLAY GROUND || 1ST PHASE", "COCACOLA FACTORY", "POLICE RPF TARINEE", "INDOOR STADIUM", "MASID || KAMAN", "ST. ANNS SCHOOL || GLOBAL COLLEGE", "BUS PASS COUNTER || INNER RING ROAD"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "9X") {
    arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
    arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "218") {
    arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "KUKATPALLY", "KPHB COLONY", "JNTUH COLLEGE", "NIZAMPET X ROADS", "MIYAPUR METRO", "MIYAPUR X ROADS", "HUDA COLONY", "CHANDANAGAR", "LINGAMPALLY", "ASHOK NAGAR", "PATANCHERUVU"]
    arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "219") {
    arrayHUP = ["SECUNDERABAD", "PATNY", "SWIMMING POOL", "PARADISE", "BALAMRAI", "TADBUN", "BOWENPALLY", "FEROZGUDA", "SHOBANA", "BALANAGAR", "Y JUNCTION", "KUKATPALLY", "KPHB COLONY", "JNTUH COLLEGE", "NIZAMPET X ROADS", "MIYAPUR METRO", "MIYAPUR X ROADS", "HUDA COLONY", "CHANDANAGAR", "LINGAMPALLY", "ASHOK NAGAR", "PATANCHERUVU"]
    arraySHUP = ["RAILWAY STATION || ALPHA HOTEL", "SURYA TOWERS || METRO STATION", "UNDEFINDED", "HOTEL || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}
else if (input1.value === "29B") {
    arrayHUP = ["SECUNDERABAD", "PATNY", "SWIMMING POOL", "PARADISE", "BALAMRAI", "TADBUN", "BOWENPALLY", "FEROZGUDA", "SHOBANA", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
    arraySHUP = ["RAILWAY STATION || ALPHA HOTEL", "SURYA TOWERS || METRO STATION", "UNDEFINDED", "HOTEL || METRO STATION"]
    routeDetailsNoteUp.style.display = "none";
    routeDetailsNoteDown.style.display = "none";
}









switch (input1.value) {
    case "1":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1/25S":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1B":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1D":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1D/229":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1D/299":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1H/D":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1J":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1L":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1M/D":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1P":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1P/25S":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1V":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1X":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1Z":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "1Z/229":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "2":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "2/25S":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "2C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "2J":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "2K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "2U":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "2Z":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3D":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3DN":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3H":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3HN":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "3K/92A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "3K/102B":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "3K/242":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "3K/252":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "3K/281":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3KN":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "3KN/102B":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3KJ":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3L":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3M":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3N":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3N/203A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3T":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "3Y":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "5K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "5K/16A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "5K/16C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "5K/16CD":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "5K/16D":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "5K/92A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "5K/188":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "5K/229":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "5M":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";


        break;

    case "6KR":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "7Z":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "8A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "8U/A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "8C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "9F":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "9K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "9K/272G":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "9K/230P":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "9X":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;



    case "9X/272G":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;



    case "9X/230P":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "9M/X":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10F":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10H":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10HA":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10HL":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10KJ":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10KL":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10KM":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10KM/224G":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10W":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10Y":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "10YF":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "14P":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "15D":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "15H":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "15H/242RG":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16A/5K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16A/49M":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16C/5K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16C/49M":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16CD":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16CD/5K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16CD/49M":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16D":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16D/5K":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16D/49M":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16H":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "16NY":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "17D":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "17H":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "17HC":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "17HN":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "17H/29B":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "17H/219":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "17V":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "18C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "18C/30":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "18C/219":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "18C/229":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "19F":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "19KJ":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "19M":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "20P":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "24L/281":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "24S":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "24S/273":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "25S":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "25S/229":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "26M":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "26N":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "29B":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "29B/17H":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "29B/272G":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "29B/272I":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "30":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "30/18C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "30/280":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "38EX":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "38T":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "40":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "45F":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "47L":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "47L/16A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    case "49":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "49A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "49M":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "49M/16A":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "49M/16C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "49M/16CD":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "49M/250":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "49M/250C":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "50B":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "218":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;

    case "219":
        arrayHUP = ["CITY BUS STATION", "AFZALGUNJ", "OSMANGUNJ", "LAKDIKAPUL", "GANDHI BHAVAN", "ASSEMBLY", "NAMPALLY", 'PUBLIC GARDENS', "KHAIRATHABAD", "PANJAGUTTA", "AMEERPET", "MYTHRIVANAM", "SR NAGAR", "VR NAGAR", "ESI HOSPITAL", "ERRAGADDA", "BHARATH NAGAR", "MOOSAPET", "Y JUNCTION", "BALANAGAR", "WATER TANK", "IDPL COLONY", "GAJULARAMARAM X ROADS", "CHINTAL", "SHAHPUR NAGAR", "JEEDIMETLA SUB STATION", "JEEDIMETLA"]
        arraySHUP = ["MGBS || METRO STATION", "CENTRAL LIBRARY || BUS STATION", "MJ MARKET", "MMTS STATION", "TELANGANA ASSEMBLY"]
        routeDetailsNoteUp.style.display = "none";
        routeDetailsNoteDown.style.display = "none";

        break;


    default:
        alert("Sorry! We are currently Working on this Route. Kindly Try After Some Time");
        subMenuPageUp.style.display = "none";
        subMenuPageDown.style.display = "none";

}